version: "3.8"

services:
  web:
    build: .
    container_name: hydrologics_django
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app
  db:
    image: postgres:14
    container_name: hydrologics_postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
